### PR TITLE
#83 correction to get_python_path for conda env

### PR DESCRIPTION
**Pull request by bago13**
Fixes python detection for conda environnment + allows to use resolve_python even if a virtual environnement is found

### CODE REVIEW

**Comment by mfussenegger** [comment]
>  allows to use resolve_python even if a virtual environnement is found

Can you elaborate why the it shouldn't use the virtual environment if the variable is set? In which scenario would one want to use a different python?

The idea was that one can have additional logic, without having to repeat the environment variable lookup. Strictly speaking this would be a breaking change.

Was there a change regarding the `Scripts` folder?

**Comment by bago13** [comment]
I used it because the default behaviour wasn't working for me,
I have no other use case in mind but I feel that if I use explicitly resolve_python it should be used or I should be warned that it wasn't considered.
It might be good to be able to bypass the default behaviour just in case.

**Comment by bago13** [comment]
Here is anaconda documentation about python executable path on linux windows and macos.

https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/

It's never in a Scripts folder, so that should be ok.

**Comment by mfussenegger** [comment]
> It's never in a Scripts folder, so that should be ok.

Thanks for the link. Yes that change is okay. Could you update the PR to only change that part?

**Comment by mfussenegger** [comment]
Merged as https://github.com/mfussenegger/nvim-dap-python/pull/88

**Pull request closed without merging**
