### PR TITLE
Review/add behave support

### PR DESCRIPTION
**Pull request by ww-daniel-mora**
Add support for BDD tests via behave

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Thanks for the contribution.

It's okay for me to add this, but I'm wondering if this could be added without distinguishing between bdd test runners and regular test runners to keep the API surface smaller.

The `TestRunner` signature could be changed to `fun(context: table): string module, string[] args`. The `context` would contain classname and methodname for python files, and line-number, feature, scenario for cucumber files.

That should make it possible to re-use `trigger_test` and make `trigger_bdd_test` unnecessary.


I also wonder if there are terms that would fit both class/feature and method/scenario, that would allow to have a single method for class & feature and another method for method & scenario, both of which do the right thing based on the filetype. Although I guess it's not a big deal to add new dedicated methods.


Lastly: Please don't re-format unrelated code. It makes it harder to review and causes unnecessary noise down the road when using git blame

**Comment by ww-daniel-mora** [comment]
@mfussenegger The filetype checking and the tree sitter queries caused me to split the API and make BDD a separate type. I like the idea of not expanding the API surface but I just could not come up with a way to achieve that. I can spend some more time thinking about it, but, if you have suggestions I'm all ears.

In practice I am using autocommands to map keys to `trigger_test` and `trigger_bdd_test` depending on the file type so the user API (keyboard commands) can still be narrow and I was comfortable putting that file type detection and smarts at the user level rather than inside nvim-dap-python.

Re: formatting - got it. I just have format-on-save enabled and decided it was more good than harm to leave the formatting changes in rather back them out with format-on-save turned off. GitHub has a flag to hide whitespace changes as well which I find helpful.

**Comment by wookayin** [comment]
My two cents:  Isn't this too specific to have for nvim-dap-python? I don't think the testing framework choice (https://github.com/behave/behave) here is quite usual, compared to unit test frameworks (standard unittest, pytest, etc.) which nvim-dap-python doesn't support as a built-in. 

I believe such bdd integration could be implemented outside as a separate plugin for the sake of less decoupling, like [neotest-python implements a DAP strategy](https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/client/strategies/dap/init.lua).

**Comment by mfussenegger** [comment]
I gave this some more thought and I think I agree with @wookayin.

The logic doesn't use any internals of nvim-dap-python so it could easily be implemented in a separate plugin. As long as users have a python adapter definition - either from nvim-dap-python or by setting it manually - it would work and compose well.

**Pull request closed without merging**
